version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Dhaka"
    open-pull-requests-limit: 50
    labels:
      - "dependencies"
      - "omnibot-auto"
    commit-message:
      prefix: "chore(deps)"
    reviewers:
      - "onelpawarai"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "github-actions"
      - "omnibot-auto"
    commit-message:
      prefix: "ci(deps)"
    groups:
      actions:
        patterns:
          - "*"
